spring.profiles.active: dev

server:
  error:
    include-message: always
  port: 8080

application:
  office-location:
    latitude: 53.339428
    longitude: -6.257664
  earth-radius-km: 6371

---

spring:
  config:
    activate:
      on-profile: dev

application:
  customer-list: customers.txt
  range-within-km: 100

---

spring:
  config:
    activate:
      on-profile: test

application:
  customer-list: customers.txt
  range-within-km: 100

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 443

application:
  customer-list: customers.txt
  range-within-km: 100
